Auto Publish Build Images

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -49,4 +49,20 @@ jobs:
 
       - name: Run PlatformIO Build
         run: |
-          pio run
+          pio run -t buildfs -t merge_bin
+
+      - name: Rename Merged Binaries
+        run: |
+          mkdir -p artifacts
+          [ -f .pio/build/pico32/firmware_merged.bin ] && cp .pio/build/pico32/firmware_merged.bin artifacts/bl_firmware_pico32.bin || echo "pico32 merged bin not found"
+          [ -f .pio/build/s3/firmware_merged.bin ] && cp .pio/build/s3/firmware_merged.bin artifacts/bl_firmware_s3.bin || echo "s3 merged bin not found"
+          [ -f .pio/build/c3/firmware_merged.bin ] && cp .pio/build/c3/firmware_merged.bin artifacts/bl_firmware_c3.bin || echo "c3 merged bin not found"
+
+      - name: Upload Firmware Binaries
+        uses: actions/upload-artifact@v4
+        with:
+          name: BambuLights-Firmware
+          path: |
+            artifacts/*.bin
+            .pio/build/**/firmware.bin
+            .pio/build/**/littlefs.bin
